version: "3.9"
services:
  php-apache:
    image: php-apache
    build: .
    ports:
      - "3000:80"
    depends_on:
      - mysqldb
    links:
      - mysqldb  
  mysqldb:
    container_name: mysql
    image: mysql
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dados
    volumes: 
      - ./dados.sql:/docker-entrypoint-initdb.d/dados.sql
      - db_data:/var/lib/mysql
    networks:
      - default
volumes:
  db_data:
